### ISSUE TITLE
Please increase font-size in screencasts

### ISSUE THREAD

**Issue by siddharthkp** [hswolff/theconsolelog#15]
🙏

<img width="1062" alt="screen shot 2018-02-15 at 12 02 25 am" src="https://user-images.githubusercontent.com/1863771/36221268-8f6695ae-11e3-11e8-9431-8f18f6765bb0.png">

Side thought: Do folks watch these on mobile?

**Comment by hswolff** [comment]
Good point on increased font size! Will try and remember for next time :D

**Comment by hswolff** [comment]
I think I remembered!
