### ISSUE TITLE
Also create this as a podcast

### ISSUE THREAD

**Issue by hswolff** [hswolff/theconsolelog#16]
For easy audio only listening!

Creating this here to gauge interest in this.

Requires a bit more plumbing to get this in place so would love feedback on this before I take the time to set it up.

**Comment by DevanB** [comment]
I'd be interested in helping see this through.

I don't personally produce a podcast but listen to hours of them per week. Beyond that, I've heard good things about [Anchor](https://anchor.fm).

**Comment by hswolff** [comment]
I took a look at Anchor and it seems it's only self contained with its own platform? It was a little confusing tbh.

I took a look [at this Lifehacker](https://lifehacker.com/how-to-start-your-own-podcast-1709798447) article on starting a podcast and I think the hardest thing I'd need to figure out is where to host the content.

One of the best perks of YouTube is there's no out of pocket expense for me. They host all the video content for free. For Podcasts I'll definitely need to spend some money to find a host. I can't find one that's free as far as I can tell.

**Comment by DevanB** [comment]
I thought that as well, but I listen to [this podcast](https://twitter.com/_RelayFM/status/966685289879080962) in Overcast, which makes me believe it isn't self-contained?

Check out point 3 on [this page](https://anchor.fm/how-to-make-a-podcast). Sounds straight-forward that you can publish externally of Anchor's platform.

Also, if you are interested in a small Mac app that will help encode and mark chapters, you might be interested [in Forecast](https://overcast.fm/forecast). 

(I might be a podcast nerd hah)
